// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MVCLaManuAgendaCourtage.Models
{
    [Table("appointments")]
    public partial class Appointments
    {
        [Key]
        [Column("idAppointment")]
        public int IdAppointment { get; set; }
        [Column("dateHour", TypeName = "datetime")]
        public DateTime DateHour { get; set; }
        [Required]
        [Column("subject", TypeName = "text")]
        public string Subject { get; set; }
        [Column("idBroker")]
        public int IdBroker { get; set; }
        [Column("idCustomer")]
        public int IdCustomer { get; set; }

        [ForeignKey("IdBroker")]
        [InverseProperty("Appointments")]
        public virtual Brokers IdBrokerNavigation { get; set; }
        [ForeignKey("IdCustomer")]
        [InverseProperty("Appointments")]
        public virtual Customers IdCustomerNavigation { get; set; }
    }
}